@"
SELECT DISK 1
CONVERT DYNAMIC
SELECT DISK 2
CONVERT DYNAMIC
SELECT DISK 3
CONVERT DYNAMIC
SELECT DISK 4
CONVERT DYNAMIC
CREATE VOLUME RAID DISK=1,2,3,4
FORMAT FS=NTFS QUICK
ASSIGN LETTER=V
"@ | DISKPART